import { createDirecotry, createFiles, removeFile } from "../problem1.js";

let data = [
  {
    id: 1,
    name: "John Doe",
    email: "john.doe@example.com",
    age: 30,
    address: {
      street: "123 Main St",
      city: "New York",
      state: "NY",
      zip: "10001",
    },
    phone: "+1-555-1234",
    orders: [
      {
        orderId: 101,
        product: "Laptop",
        price: 1200,
        date: "2024-01-15",
      },
      {
        orderId: 102,
        product: "Smartphone",
        price: 800,
        date: "2024-02-10",
      },
    ],
  },
  {
    id: 2,
    name: "Jane Smith",
    email: "jane.smith@example.com",
    age: 28,
    address: {
      street: "456 Oak St",
      city: "San Francisco",
      state: "CA",
      zip: "94102",
    },
    phone: "+1-555-5678",
    orders: [
      {
        orderId: 103,
        product: "Tablet",
        price: 500,
        date: "2024-03-05",
      },
      {
        orderId: 104,
        product: "Wireless Headphones",
        price: 150,
        date: "2024-03-20",
      },
    ],
  },
  {
    id: 3,
    name: "Alice Johnson",
    email: "alice.johnson@example.com",
    age: 35,
    address: {
      street: "789 Pine St",
      city: "Chicago",
      state: "IL",
      zip: "60601",
    },
    phone: "+1-555-9012",
    orders: [
      {
        orderId: 105,
        product: "Gaming Console",
        price: 400,
        date: "2024-04-10",
      },
      {
        orderId: 106,
        product: "4K TV",
        price: 900,
        date: "2024-05-01",
      },
    ],
  },
  {
    id: 4,
    name: "Michael Brown",
    email: "michael.brown@example.com",
    age: 40,
    address: {
      street: "135 Maple St",
      city: "Los Angeles",
      state: "CA",
      zip: "90001",
    },
    phone: "+1-555-3456",
    orders: [
      {
        orderId: 107,
        product: "Smartwatch",
        price: 250,
        date: "2024-06-12",
      },
      {
        orderId: 108,
        product: "Bluetooth Speaker",
        price: 100,
        date: "2024-07-18",
      },
    ],
  },
  {
    id: 5,
    name: "Emily White",
    email: "emily.white@example.com",
    age: 32,
    address: {
      street: "246 Birch St",
      city: "Houston",
      state: "TX",
      zip: "77002",
    },
    phone: "+1-555-7890",
    orders: [
      {
        orderId: 109,
        product: "Camera",
        price: 700,
        date: "2024-08-05",
      },
      {
        orderId: 110,
        product: "Tripod",
        price: 80,
        date: "2024-08-25",
      },
    ],
  },
  {
    id: 6,
    name: "David Green",
    email: "david.green@example.com",
    age: 27,
    address: {
      street: "789 Walnut St",
      city: "Seattle",
      state: "WA",
      zip: "98101",
    },
    phone: "+1-555-2345",
    orders: [
      {
        orderId: 111,
        product: "Desktop PC",
        price: 1500,
        date: "2024-09-10",
      },
      {
        orderId: 112,
        product: "Mechanical Keyboard",
        price: 120,
        date: "2024-09-30",
      },
    ],
  },
  {
    id: 1,
    name: "John Doe",
    email: "john.doe@example.com",
    age: 30,
    address: {
      street: "123 Main St",
      city: "New York",
      state: "NY",
      zip: "10001",
    },
    phone: "+1-555-1234",
    orders: [
      {
        orderId: 101,
        product: "Laptop",
        price: 1200,
        date: "2024-01-15",
      },
      {
        orderId: 102,
        product: "Smartphone",
        price: 800,
        date: "2024-02-10",
      },
    ],
  },
  {
    id: 2,
    name: "Jane Smith",
    email: "jane.smith@example.com",
    age: 28,
    address: {
      street: "456 Oak St",
      city: "San Francisco",
      state: "CA",
      zip: "94102",
    },
    phone: "+1-555-5678",
    orders: [
      {
        orderId: 103,
        product: "Tablet",
        price: 500,
        date: "2024-03-05",
      },
      {
        orderId: 104,
        product: "Wireless Headphones",
        price: 150,
        date: "2024-03-20",
      },
    ],
  },
  {
    id: 3,
    name: "Alice Johnson",
    email: "alice.johnson@example.com",
    age: 35,
    address: {
      street: "789 Pine St",
      city: "Chicago",
      state: "IL",
      zip: "60601",
    },
    phone: "+1-555-9012",
    orders: [
      {
        orderId: 105,
        product: "Gaming Console",
        price: 400,
        date: "2024-04-10",
      },
      {
        orderId: 106,
        product: "4K TV",
        price: 900,
        date: "2024-05-01",
      },
    ],
  },
  {
    id: 4,
    name: "Michael Brown",
    email: "michael.brown@example.com",
    age: 40,
    address: {
      street: "135 Maple St",
      city: "Los Angeles",
      state: "CA",
      zip: "90001",
    },
    phone: "+1-555-3456",
    orders: [
      {
        orderId: 107,
        product: "Smartwatch",
        price: 250,
        date: "2024-06-12",
      },
      {
        orderId: 108,
        product: "Bluetooth Speaker",
        price: 100,
        date: "2024-07-18",
      },
    ],
  },
  {
    id: 5,
    name: "Emily White",
    email: "emily.white@example.com",
    age: 32,
    address: {
      street: "246 Birch St",
      city: "Houston",
      state: "TX",
      zip: "77002",
    },
    phone: "+1-555-7890",
    orders: [
      {
        orderId: 109,
        product: "Camera",
        price: 700,
        date: "2024-08-05",
      },
      {
        orderId: 110,
        product: "Tripod",
        price: 80,
        date: "2024-08-25",
      },
    ],
  },
  {
    id: 6,
    name: "David Green",
    email: "david.green@example.com",
    age: 27,
    address: {
      street: "789 Walnut St",
      city: "Seattle",
      state: "WA",
      zip: "98101",
    },
    phone: "+1-555-2345",
    orders: [
      {
        orderId: 111,
        product: "Desktop PC",
        price: 1500,
        date: "2024-09-10",
      },
      {
        orderId: 112,
        product: "Mechanical Keyboard",
        price: 120,
        date: "2024-09-30",
      },
    ],
  },
  {
    id: 1,
    name: "John Doe",
    email: "john.doe@example.com",
    age: 30,
    address: {
      street: "123 Main St",
      city: "New York",
      state: "NY",
      zip: "10001",
    },
    phone: "+1-555-1234",
    orders: [
      {
        orderId: 101,
        product: "Laptop",
        price: 1200,
        date: "2024-01-15",
      },
      {
        orderId: 102,
        product: "Smartphone",
        price: 800,
        date: "2024-02-10",
      },
    ],
  },
  {
    id: 2,
    name: "Jane Smith",
    email: "jane.smith@example.com",
    age: 28,
    address: {
      street: "456 Oak St",
      city: "San Francisco",
      state: "CA",
      zip: "94102",
    },
    phone: "+1-555-5678",
    orders: [
      {
        orderId: 103,
        product: "Tablet",
        price: 500,
        date: "2024-03-05",
      },
      {
        orderId: 104,
        product: "Wireless Headphones",
        price: 150,
        date: "2024-03-20",
      },
    ],
  },
  {
    id: 3,
    name: "Alice Johnson",
    email: "alice.johnson@example.com",
    age: 35,
    address: {
      street: "789 Pine St",
      city: "Chicago",
      state: "IL",
      zip: "60601",
    },
    phone: "+1-555-9012",
    orders: [
      {
        orderId: 105,
        product: "Gaming Console",
        price: 400,
        date: "2024-04-10",
      },
      {
        orderId: 106,
        product: "4K TV",
        price: 900,
        date: "2024-05-01",
      },
    ],
  },
  {
    id: 4,
    name: "Michael Brown",
    email: "michael.brown@example.com",
    age: 40,
    address: {
      street: "135 Maple St",
      city: "Los Angeles",
      state: "CA",
      zip: "90001",
    },
    phone: "+1-555-3456",
    orders: [
      {
        orderId: 107,
        product: "Smartwatch",
        price: 250,
        date: "2024-06-12",
      },
      {
        orderId: 108,
        product: "Bluetooth Speaker",
        price: 100,
        date: "2024-07-18",
      },
    ],
  },
  {
    id: 5,
    name: "Emily White",
    email: "emily.white@example.com",
    age: 32,
    address: {
      street: "246 Birch St",
      city: "Houston",
      state: "TX",
      zip: "77002",
    },
    phone: "+1-555-7890",
    orders: [
      {
        orderId: 109,
        product: "Camera",
        price: 700,
        date: "2024-08-05",
      },
      {
        orderId: 110,
        product: "Tripod",
        price: 80,
        date: "2024-08-25",
      },
    ],
  },
  {
    id: 6,
    name: "David Green",
    email: "david.green@example.com",
    age: 27,
    address: {
      street: "789 Walnut St",
      city: "Seattle",
      state: "WA",
      zip: "98101",
    },
    phone: "+1-555-2345",
    orders: [
      {
        orderId: 111,
        product: "Desktop PC",
        price: 1500,
        date: "2024-09-10",
      },
      {
        orderId: 112,
        product: "Mechanical Keyboard",
        price: 120,
        date: "2024-09-30",
      },
    ],
  },
  {
    id: 1,
    name: "John Doe",
    email: "john.doe@example.com",
    age: 30,
    address: {
      street: "123 Main St",
      city: "New York",
      state: "NY",
      zip: "10001",
    },
    phone: "+1-555-1234",
    orders: [
      {
        orderId: 101,
        product: "Laptop",
        price: 1200,
        date: "2024-01-15",
      },
      {
        orderId: 102,
        product: "Smartphone",
        price: 800,
        date: "2024-02-10",
      },
    ],
  },
  {
    id: 2,
    name: "Jane Smith",
    email: "jane.smith@example.com",
    age: 28,
    address: {
      street: "456 Oak St",
      city: "San Francisco",
      state: "CA",
      zip: "94102",
    },
    phone: "+1-555-5678",
    orders: [
      {
        orderId: 103,
        product: "Tablet",
        price: 500,
        date: "2024-03-05",
      },
      {
        orderId: 104,
        product: "Wireless Headphones",
        price: 150,
        date: "2024-03-20",
      },
    ],
  },
  {
    id: 3,
    name: "Alice Johnson",
    email: "alice.johnson@example.com",
    age: 35,
    address: {
      street: "789 Pine St",
      city: "Chicago",
      state: "IL",
      zip: "60601",
    },
    phone: "+1-555-9012",
    orders: [
      {
        orderId: 105,
        product: "Gaming Console",
        price: 400,
        date: "2024-04-10",
      },
      {
        orderId: 106,
        product: "4K TV",
        price: 900,
        date: "2024-05-01",
      },
    ],
  },
  {
    id: 4,
    name: "Michael Brown",
    email: "michael.brown@example.com",
    age: 40,
    address: {
      street: "135 Maple St",
      city: "Los Angeles",
      state: "CA",
      zip: "90001",
    },
    phone: "+1-555-3456",
    orders: [
      {
        orderId: 107,
        product: "Smartwatch",
        price: 250,
        date: "2024-06-12",
      },
      {
        orderId: 108,
        product: "Bluetooth Speaker",
        price: 100,
        date: "2024-07-18",
      },
    ],
  },
  {
    id: 5,
    name: "Emily White",
    email: "emily.white@example.com",
    age: 32,
    address: {
      street: "246 Birch St",
      city: "Houston",
      state: "TX",
      zip: "77002",
    },
    phone: "+1-555-7890",
    orders: [
      {
        orderId: 109,
        product: "Camera",
        price: 700,
        date: "2024-08-05",
      },
      {
        orderId: 110,
        product: "Tripod",
        price: 80,
        date: "2024-08-25",
      },
    ],
  },
  {
    id: 6,
    name: "David Green",
    email: "david.green@example.com",
    age: 27,
    address: {
      street: "789 Walnut St",
      city: "Seattle",
      state: "WA",
      zip: "98101",
    },
    phone: "+1-555-2345",
    orders: [
      {
        orderId: 111,
        product: "Desktop PC",
        price: 1500,
        date: "2024-09-10",
      },
      {
        orderId: 112,
        product: "Mechanical Keyboard",
        price: 120,
        date: "2024-09-30",
      },
    ],
  },
  {
    id: 1,
    name: "John Doe",
    email: "john.doe@example.com",
    age: 30,
    address: {
      street: "123 Main St",
      city: "New York",
      state: "NY",
      zip: "10001",
    },
    phone: "+1-555-1234",
    orders: [
      {
        orderId: 101,
        product: "Laptop",
        price: 1200,
        date: "2024-01-15",
      },
      {
        orderId: 102,
        product: "Smartphone",
        price: 800,
        date: "2024-02-10",
      },
    ],
  },
  {
    id: 2,
    name: "Jane Smith",
    email: "jane.smith@example.com",
    age: 28,
    address: {
      street: "456 Oak St",
      city: "San Francisco",
      state: "CA",
      zip: "94102",
    },
    phone: "+1-555-5678",
    orders: [
      {
        orderId: 103,
        product: "Tablet",
        price: 500,
        date: "2024-03-05",
      },
      {
        orderId: 104,
        product: "Wireless Headphones",
        price: 150,
        date: "2024-03-20",
      },
    ],
  },
  {
    id: 3,
    name: "Alice Johnson",
    email: "alice.johnson@example.com",
    age: 35,
    address: {
      street: "789 Pine St",
      city: "Chicago",
      state: "IL",
      zip: "60601",
    },
    phone: "+1-555-9012",
    orders: [
      {
        orderId: 105,
        product: "Gaming Console",
        price: 400,
        date: "2024-04-10",
      },
      {
        orderId: 106,
        product: "4K TV",
        price: 900,
        date: "2024-05-01",
      },
    ],
  },
  {
    id: 4,
    name: "Michael Brown",
    email: "michael.brown@example.com",
    age: 40,
    address: {
      street: "135 Maple St",
      city: "Los Angeles",
      state: "CA",
      zip: "90001",
    },
    phone: "+1-555-3456",
    orders: [
      {
        orderId: 107,
        product: "Smartwatch",
        price: 250,
        date: "2024-06-12",
      },
      {
        orderId: 108,
        product: "Bluetooth Speaker",
        price: 100,
        date: "2024-07-18",
      },
    ],
  },
  {
    id: 5,
    name: "Emily White",
    email: "emily.white@example.com",
    age: 32,
    address: {
      street: "246 Birch St",
      city: "Houston",
      state: "TX",
      zip: "77002",
    },
    phone: "+1-555-7890",
    orders: [
      {
        orderId: 109,
        product: "Camera",
        price: 700,
        date: "2024-08-05",
      },
      {
        orderId: 110,
        product: "Tripod",
        price: 80,
        date: "2024-08-25",
      },
    ],
  },
  {
    id: 6,
    name: "David Green",
    email: "david.green@example.com",
    age: 27,
    address: {
      street: "789 Walnut St",
      city: "Seattle",
      state: "WA",
      zip: "98101",
    },
    phone: "+1-555-2345",
    orders: [
      {
        orderId: 111,
        product: "Desktop PC",
        price: 1500,
        date: "2024-09-10",
      },
      {
        orderId: 112,
        product: "Mechanical Keyboard",
        price: 120,
        date: "2024-09-30",
      },
    ],
  },
  {
    id: 1,
    name: "John Doe",
    email: "john.doe@example.com",
    age: 30,
    address: {
      street: "123 Main St",
      city: "New York",
      state: "NY",
      zip: "10001",
    },
    phone: "+1-555-1234",
    orders: [
      {
        orderId: 101,
        product: "Laptop",
        price: 1200,
        date: "2024-01-15",
      },
      {
        orderId: 102,
        product: "Smartphone",
        price: 800,
        date: "2024-02-10",
      },
    ],
  },
  {
    id: 2,
    name: "Jane Smith",
    email: "jane.smith@example.com",
    age: 28,
    address: {
      street: "456 Oak St",
      city: "San Francisco",
      state: "CA",
      zip: "94102",
    },
    phone: "+1-555-5678",
    orders: [
      {
        orderId: 103,
        product: "Tablet",
        price: 500,
        date: "2024-03-05",
      },
      {
        orderId: 104,
        product: "Wireless Headphones",
        price: 150,
        date: "2024-03-20",
      },
    ],
  },
  {
    id: 3,
    name: "Alice Johnson",
    email: "alice.johnson@example.com",
    age: 35,
    address: {
      street: "789 Pine St",
      city: "Chicago",
      state: "IL",
      zip: "60601",
    },
    phone: "+1-555-9012",
    orders: [
      {
        orderId: 105,
        product: "Gaming Console",
        price: 400,
        date: "2024-04-10",
      },
      {
        orderId: 106,
        product: "4K TV",
        price: 900,
        date: "2024-05-01",
      },
    ],
  },
  {
    id: 4,
    name: "Michael Brown",
    email: "michael.brown@example.com",
    age: 40,
    address: {
      street: "135 Maple St",
      city: "Los Angeles",
      state: "CA",
      zip: "90001",
    },
    phone: "+1-555-3456",
    orders: [
      {
        orderId: 107,
        product: "Smartwatch",
        price: 250,
        date: "2024-06-12",
      },
      {
        orderId: 108,
        product: "Bluetooth Speaker",
        price: 100,
        date: "2024-07-18",
      },
    ],
  },
  {
    id: 5,
    name: "Emily White",
    email: "emily.white@example.com",
    age: 32,
    address: {
      street: "246 Birch St",
      city: "Houston",
      state: "TX",
      zip: "77002",
    },
    phone: "+1-555-7890",
    orders: [
      {
        orderId: 109,
        product: "Camera",
        price: 700,
        date: "2024-08-05",
      },
      {
        orderId: 110,
        product: "Tripod",
        price: 80,
        date: "2024-08-25",
      },
    ],
  },
  {
    id: 6,
    name: "David Green",
    email: "david.green@example.com",
    age: 27,
    address: {
      street: "789 Walnut St",
      city: "Seattle",
      state: "WA",
      zip: "98101",
    },
    phone: "+1-555-2345",
    orders: [
      {
        orderId: 111,
        product: "Desktop PC",
        price: 1500,
        date: "2024-09-10",
      },
      {
        orderId: 112,
        product: "Mechanical Keyboard",
        price: 120,
        date: "2024-09-30",
      },
    ],
  },
  {
    id: 1,
    name: "John Doe",
    email: "john.doe@example.com",
    age: 30,
    address: {
      street: "123 Main St",
      city: "New York",
      state: "NY",
      zip: "10001",
    },
    phone: "+1-555-1234",
    orders: [
      {
        orderId: 101,
        product: "Laptop",
        price: 1200,
        date: "2024-01-15",
      },
      {
        orderId: 102,
        product: "Smartphone",
        price: 800,
        date: "2024-02-10",
      },
    ],
  },
  {
    id: 2,
    name: "Jane Smith",
    email: "jane.smith@example.com",
    age: 28,
    address: {
      street: "456 Oak St",
      city: "San Francisco",
      state: "CA",
      zip: "94102",
    },
    phone: "+1-555-5678",
    orders: [
      {
        orderId: 103,
        product: "Tablet",
        price: 500,
        date: "2024-03-05",
      },
      {
        orderId: 104,
        product: "Wireless Headphones",
        price: 150,
        date: "2024-03-20",
      },
    ],
  },
  {
    id: 3,
    name: "Alice Johnson",
    email: "alice.johnson@example.com",
    age: 35,
    address: {
      street: "789 Pine St",
      city: "Chicago",
      state: "IL",
      zip: "60601",
    },
    phone: "+1-555-9012",
    orders: [
      {
        orderId: 105,
        product: "Gaming Console",
        price: 400,
        date: "2024-04-10",
      },
      {
        orderId: 106,
        product: "4K TV",
        price: 900,
        date: "2024-05-01",
      },
    ],
  },
  {
    id: 4,
    name: "Michael Brown",
    email: "michael.brown@example.com",
    age: 40,
    address: {
      street: "135 Maple St",
      city: "Los Angeles",
      state: "CA",
      zip: "90001",
    },
    phone: "+1-555-3456",
    orders: [
      {
        orderId: 107,
        product: "Smartwatch",
        price: 250,
        date: "2024-06-12",
      },
      {
        orderId: 108,
        product: "Bluetooth Speaker",
        price: 100,
        date: "2024-07-18",
      },
    ],
  },
  {
    id: 5,
    name: "Emily White",
    email: "emily.white@example.com",
    age: 32,
    address: {
      street: "246 Birch St",
      city: "Houston",
      state: "TX",
      zip: "77002",
    },
    phone: "+1-555-7890",
    orders: [
      {
        orderId: 109,
        product: "Camera",
        price: 700,
        date: "2024-08-05",
      },
      {
        orderId: 110,
        product: "Tripod",
        price: 80,
        date: "2024-08-25",
      },
    ],
  },
  {
    id: 6,
    name: "David Green",
    email: "david.green@example.com",
    age: 27,
    address: {
      street: "789 Walnut St",
      city: "Seattle",
      state: "WA",
      zip: "98101",
    },
    phone: "+1-555-2345",
    orders: [
      {
        orderId: 111,
        product: "Desktop PC",
        price: 1500,
        date: "2024-09-10",
      },
      {
        orderId: 112,
        product: "Mechanical Keyboard",
        price: 120,
        date: "2024-09-30",
      },
    ],
  },
  {
    id: 1,
    name: "John Doe",
    email: "john.doe@example.com",
    age: 30,
    address: {
      street: "123 Main St",
      city: "New York",
      state: "NY",
      zip: "10001",
    },
    phone: "+1-555-1234",
    orders: [
      {
        orderId: 101,
        product: "Laptop",
        price: 1200,
        date: "2024-01-15",
      },
      {
        orderId: 102,
        product: "Smartphone",
        price: 800,
        date: "2024-02-10",
      },
    ],
  },
  {
    id: 2,
    name: "Jane Smith",
    email: "jane.smith@example.com",
    age: 28,
    address: {
      street: "456 Oak St",
      city: "San Francisco",
      state: "CA",
      zip: "94102",
    },
    phone: "+1-555-5678",
    orders: [
      {
        orderId: 103,
        product: "Tablet",
        price: 500,
        date: "2024-03-05",
      },
      {
        orderId: 104,
        product: "Wireless Headphones",
        price: 150,
        date: "2024-03-20",
      },
    ],
  },
  {
    id: 3,
    name: "Alice Johnson",
    email: "alice.johnson@example.com",
    age: 35,
    address: {
      street: "789 Pine St",
      city: "Chicago",
      state: "IL",
      zip: "60601",
    },
    phone: "+1-555-9012",
    orders: [
      {
        orderId: 105,
        product: "Gaming Console",
        price: 400,
        date: "2024-04-10",
      },
      {
        orderId: 106,
        product: "4K TV",
        price: 900,
        date: "2024-05-01",
      },
    ],
  },
  {
    id: 4,
    name: "Michael Brown",
    email: "michael.brown@example.com",
    age: 40,
    address: {
      street: "135 Maple St",
      city: "Los Angeles",
      state: "CA",
      zip: "90001",
    },
    phone: "+1-555-3456",
    orders: [
      {
        orderId: 107,
        product: "Smartwatch",
        price: 250,
        date: "2024-06-12",
      },
      {
        orderId: 108,
        product: "Bluetooth Speaker",
        price: 100,
        date: "2024-07-18",
      },
    ],
  },
  {
    id: 5,
    name: "Emily White",
    email: "emily.white@example.com",
    age: 32,
    address: {
      street: "246 Birch St",
      city: "Houston",
      state: "TX",
      zip: "77002",
    },
    phone: "+1-555-7890",
    orders: [
      {
        orderId: 109,
        product: "Camera",
        price: 700,
        date: "2024-08-05",
      },
      {
        orderId: 110,
        product: "Tripod",
        price: 80,
        date: "2024-08-25",
      },
    ],
  },
  {
    id: 6,
    name: "David Green",
    email: "david.green@example.com",
    age: 27,
    address: {
      street: "789 Walnut St",
      city: "Seattle",
      state: "WA",
      zip: "98101",
    },
    phone: "+1-555-2345",
    orders: [
      {
        orderId: 111,
        product: "Desktop PC",
        price: 1500,
        date: "2024-09-10",
      },
      {
        orderId: 112,
        product: "Mechanical Keyboard",
        price: 120,
        date: "2024-09-30",
      },
    ],
  },
  {
    id: 1,
    name: "John Doe",
    email: "john.doe@example.com",
    age: 30,
    address: {
      street: "123 Main St",
      city: "New York",
      state: "NY",
      zip: "10001",
    },
    phone: "+1-555-1234",
    orders: [
      {
        orderId: 101,
        product: "Laptop",
        price: 1200,
        date: "2024-01-15",
      },
      {
        orderId: 102,
        product: "Smartphone",
        price: 800,
        date: "2024-02-10",
      },
    ],
  },
  {
    id: 2,
    name: "Jane Smith",
    email: "jane.smith@example.com",
    age: 28,
    address: {
      street: "456 Oak St",
      city: "San Francisco",
      state: "CA",
      zip: "94102",
    },
    phone: "+1-555-5678",
    orders: [
      {
        orderId: 103,
        product: "Tablet",
        price: 500,
        date: "2024-03-05",
      },
      {
        orderId: 104,
        product: "Wireless Headphones",
        price: 150,
        date: "2024-03-20",
      },
    ],
  },
  {
    id: 3,
    name: "Alice Johnson",
    email: "alice.johnson@example.com",
    age: 35,
    address: {
      street: "789 Pine St",
      city: "Chicago",
      state: "IL",
      zip: "60601",
    },
    phone: "+1-555-9012",
    orders: [
      {
        orderId: 105,
        product: "Gaming Console",
        price: 400,
        date: "2024-04-10",
      },
      {
        orderId: 106,
        product: "4K TV",
        price: 900,
        date: "2024-05-01",
      },
    ],
  },
  {
    id: 4,
    name: "Michael Brown",
    email: "michael.brown@example.com",
    age: 40,
    address: {
      street: "135 Maple St",
      city: "Los Angeles",
      state: "CA",
      zip: "90001",
    },
    phone: "+1-555-3456",
    orders: [
      {
        orderId: 107,
        product: "Smartwatch",
        price: 250,
        date: "2024-06-12",
      },
      {
        orderId: 108,
        product: "Bluetooth Speaker",
        price: 100,
        date: "2024-07-18",
      },
    ],
  },
  {
    id: 5,
    name: "Emily White",
    email: "emily.white@example.com",
    age: 32,
    address: {
      street: "246 Birch St",
      city: "Houston",
      state: "TX",
      zip: "77002",
    },
    phone: "+1-555-7890",
    orders: [
      {
        orderId: 109,
        product: "Camera",
        price: 700,
        date: "2024-08-05",
      },
      {
        orderId: 110,
        product: "Tripod",
        price: 80,
        date: "2024-08-25",
      },
    ],
  },
  {
    id: 6,
    name: "David Green",
    email: "david.green@example.com",
    age: 27,
    address: {
      street: "789 Walnut St",
      city: "Seattle",
      state: "WA",
      zip: "98101",
    },
    phone: "+1-555-2345",
    orders: [
      {
        orderId: 111,
        product: "Desktop PC",
        price: 1500,
        date: "2024-09-10",
      },
      {
        orderId: 112,
        product: "Mechanical Keyboard",
        price: 120,
        date: "2024-09-30",
      },
    ],
  },
  {
    id: 1,
    name: "John Doe",
    email: "john.doe@example.com",
    age: 30,
    address: {
      street: "123 Main St",
      city: "New York",
      state: "NY",
      zip: "10001",
    },
    phone: "+1-555-1234",
    orders: [
      {
        orderId: 101,
        product: "Laptop",
        price: 1200,
        date: "2024-01-15",
      },
      {
        orderId: 102,
        product: "Smartphone",
        price: 800,
        date: "2024-02-10",
      },
    ],
  },
  {
    id: 2,
    name: "Jane Smith",
    email: "jane.smith@example.com",
    age: 28,
    address: {
      street: "456 Oak St",
      city: "San Francisco",
      state: "CA",
      zip: "94102",
    },
    phone: "+1-555-5678",
    orders: [
      {
        orderId: 103,
        product: "Tablet",
        price: 500,
        date: "2024-03-05",
      },
      {
        orderId: 104,
        product: "Wireless Headphones",
        price: 150,
        date: "2024-03-20",
      },
    ],
  },
  {
    id: 3,
    name: "Alice Johnson",
    email: "alice.johnson@example.com",
    age: 35,
    address: {
      street: "789 Pine St",
      city: "Chicago",
      state: "IL",
      zip: "60601",
    },
    phone: "+1-555-9012",
    orders: [
      {
        orderId: 105,
        product: "Gaming Console",
        price: 400,
        date: "2024-04-10",
      },
      {
        orderId: 106,
        product: "4K TV",
        price: 900,
        date: "2024-05-01",
      },
    ],
  },
  {
    id: 4,
    name: "Michael Brown",
    email: "michael.brown@example.com",
    age: 40,
    address: {
      street: "135 Maple St",
      city: "Los Angeles",
      state: "CA",
      zip: "90001",
    },
    phone: "+1-555-3456",
    orders: [
      {
        orderId: 107,
        product: "Smartwatch",
        price: 250,
        date: "2024-06-12",
      },
      {
        orderId: 108,
        product: "Bluetooth Speaker",
        price: 100,
        date: "2024-07-18",
      },
    ],
  },
  {
    id: 5,
    name: "Emily White",
    email: "emily.white@example.com",
    age: 32,
    address: {
      street: "246 Birch St",
      city: "Houston",
      state: "TX",
      zip: "77002",
    },
    phone: "+1-555-7890",
    orders: [
      {
        orderId: 109,
        product: "Camera",
        price: 700,
        date: "2024-08-05",
      },
      {
        orderId: 110,
        product: "Tripod",
        price: 80,
        date: "2024-08-25",
      },
    ],
  },
  {
    id: 6,
    name: "David Green",
    email: "david.green@example.com",
    age: 27,
    address: {
      street: "789 Walnut St",
      city: "Seattle",
      state: "WA",
      zip: "98101",
    },
    phone: "+1-555-2345",
    orders: [
      {
        orderId: 111,
        product: "Desktop PC",
        price: 1500,
        date: "2024-09-10",
      },
      {
        orderId: 112,
        product: "Mechanical Keyboard",
        price: 120,
        date: "2024-09-30",
      },
    ],
  },
  {
    id: 1,
    name: "John Doe",
    email: "john.doe@example.com",
    age: 30,
    address: {
      street: "123 Main St",
      city: "New York",
      state: "NY",
      zip: "10001",
    },
    phone: "+1-555-1234",
    orders: [
      {
        orderId: 101,
        product: "Laptop",
        price: 1200,
        date: "2024-01-15",
      },
      {
        orderId: 102,
        product: "Smartphone",
        price: 800,
        date: "2024-02-10",
      },
    ],
  },
  {
    id: 2,
    name: "Jane Smith",
    email: "jane.smith@example.com",
    age: 28,
    address: {
      street: "456 Oak St",
      city: "San Francisco",
      state: "CA",
      zip: "94102",
    },
    phone: "+1-555-5678",
    orders: [
      {
        orderId: 103,
        product: "Tablet",
        price: 500,
        date: "2024-03-05",
      },
      {
        orderId: 104,
        product: "Wireless Headphones",
        price: 150,
        date: "2024-03-20",
      },
    ],
  },
  {
    id: 3,
    name: "Alice Johnson",
    email: "alice.johnson@example.com",
    age: 35,
    address: {
      street: "789 Pine St",
      city: "Chicago",
      state: "IL",
      zip: "60601",
    },
    phone: "+1-555-9012",
    orders: [
      {
        orderId: 105,
        product: "Gaming Console",
        price: 400,
        date: "2024-04-10",
      },
      {
        orderId: 106,
        product: "4K TV",
        price: 900,
        date: "2024-05-01",
      },
    ],
  },
  {
    id: 4,
    name: "Michael Brown",
    email: "michael.brown@example.com",
    age: 40,
    address: {
      street: "135 Maple St",
      city: "Los Angeles",
      state: "CA",
      zip: "90001",
    },
    phone: "+1-555-3456",
    orders: [
      {
        orderId: 107,
        product: "Smartwatch",
        price: 250,
        date: "2024-06-12",
      },
      {
        orderId: 108,
        product: "Bluetooth Speaker",
        price: 100,
        date: "2024-07-18",
      },
    ],
  },
  {
    id: 5,
    name: "Emily White",
    email: "emily.white@example.com",
    age: 32,
    address: {
      street: "246 Birch St",
      city: "Houston",
      state: "TX",
      zip: "77002",
    },
    phone: "+1-555-7890",
    orders: [
      {
        orderId: 109,
        product: "Camera",
        price: 700,
        date: "2024-08-05",
      },
      {
        orderId: 110,
        product: "Tripod",
        price: 80,
        date: "2024-08-25",
      },
    ],
  },
  {
    id: 6,
    name: "David Green",
    email: "david.green@example.com",
    age: 27,
    address: {
      street: "789 Walnut St",
      city: "Seattle",
      state: "WA",
      zip: "98101",
    },
    phone: "+1-555-2345",
    orders: [
      {
        orderId: 111,
        product: "Desktop PC",
        price: 1500,
        date: "2024-09-10",
      },
      {
        orderId: 112,
        product: "Mechanical Keyboard",
        price: 120,
        date: "2024-09-30",
      },
    ],
  },
  {
    id: 1,
    name: "John Doe",
    email: "john.doe@example.com",
    age: 30,
    address: {
      street: "123 Main St",
      city: "New York",
      state: "NY",
      zip: "10001",
    },
    phone: "+1-555-1234",
    orders: [
      {
        orderId: 101,
        product: "Laptop",
        price: 1200,
        date: "2024-01-15",
      },
      {
        orderId: 102,
        product: "Smartphone",
        price: 800,
        date: "2024-02-10",
      },
    ],
  },
  {
    id: 2,
    name: "Jane Smith",
    email: "jane.smith@example.com",
    age: 28,
    address: {
      street: "456 Oak St",
      city: "San Francisco",
      state: "CA",
      zip: "94102",
    },
    phone: "+1-555-5678",
    orders: [
      {
        orderId: 103,
        product: "Tablet",
        price: 500,
        date: "2024-03-05",
      },
      {
        orderId: 104,
        product: "Wireless Headphones",
        price: 150,
        date: "2024-03-20",
      },
    ],
  },
  {
    id: 3,
    name: "Alice Johnson",
    email: "alice.johnson@example.com",
    age: 35,
    address: {
      street: "789 Pine St",
      city: "Chicago",
      state: "IL",
      zip: "60601",
    },
    phone: "+1-555-9012",
    orders: [
      {
        orderId: 105,
        product: "Gaming Console",
        price: 400,
        date: "2024-04-10",
      },
      {
        orderId: 106,
        product: "4K TV",
        price: 900,
        date: "2024-05-01",
      },
    ],
  },
  {
    id: 4,
    name: "Michael Brown",
    email: "michael.brown@example.com",
    age: 40,
    address: {
      street: "135 Maple St",
      city: "Los Angeles",
      state: "CA",
      zip: "90001",
    },
    phone: "+1-555-3456",
    orders: [
      {
        orderId: 107,
        product: "Smartwatch",
        price: 250,
        date: "2024-06-12",
      },
      {
        orderId: 108,
        product: "Bluetooth Speaker",
        price: 100,
        date: "2024-07-18",
      },
    ],
  },
  {
    id: 5,
    name: "Emily White",
    email: "emily.white@example.com",
    age: 32,
    address: {
      street: "246 Birch St",
      city: "Houston",
      state: "TX",
      zip: "77002",
    },
    phone: "+1-555-7890",
    orders: [
      {
        orderId: 109,
        product: "Camera",
        price: 700,
        date: "2024-08-05",
      },
      {
        orderId: 110,
        product: "Tripod",
        price: 80,
        date: "2024-08-25",
      },
    ],
  },
  {
    id: 6,
    name: "David Green",
    email: "david.green@example.com",
    age: 27,
    address: {
      street: "789 Walnut St",
      city: "Seattle",
      state: "WA",
      zip: "98101",
    },
    phone: "+1-555-2345",
    orders: [
      {
        orderId: 111,
        product: "Desktop PC",
        price: 1500,
        date: "2024-09-10",
      },
      {
        orderId: 112,
        product: "Mechanical Keyboard",
        price: 120,
        date: "2024-09-30",
      },
    ],
  },
  {
    id: 1,
    name: "John Doe",
    email: "john.doe@example.com",
    age: 30,
    address: {
      street: "123 Main St",
      city: "New York",
      state: "NY",
      zip: "10001",
    },
    phone: "+1-555-1234",
    orders: [
      {
        orderId: 101,
        product: "Laptop",
        price: 1200,
        date: "2024-01-15",
      },
      {
        orderId: 102,
        product: "Smartphone",
        price: 800,
        date: "2024-02-10",
      },
    ],
  },
  {
    id: 2,
    name: "Jane Smith",
    email: "jane.smith@example.com",
    age: 28,
    address: {
      street: "456 Oak St",
      city: "San Francisco",
      state: "CA",
      zip: "94102",
    },
    phone: "+1-555-5678",
    orders: [
      {
        orderId: 103,
        product: "Tablet",
        price: 500,
        date: "2024-03-05",
      },
      {
        orderId: 104,
        product: "Wireless Headphones",
        price: 150,
        date: "2024-03-20",
      },
    ],
  },
  {
    id: 3,
    name: "Alice Johnson",
    email: "alice.johnson@example.com",
    age: 35,
    address: {
      street: "789 Pine St",
      city: "Chicago",
      state: "IL",
      zip: "60601",
    },
    phone: "+1-555-9012",
    orders: [
      {
        orderId: 105,
        product: "Gaming Console",
        price: 400,
        date: "2024-04-10",
      },
      {
        orderId: 106,
        product: "4K TV",
        price: 900,
        date: "2024-05-01",
      },
    ],
  },
  {
    id: 4,
    name: "Michael Brown",
    email: "michael.brown@example.com",
    age: 40,
    address: {
      street: "135 Maple St",
      city: "Los Angeles",
      state: "CA",
      zip: "90001",
    },
    phone: "+1-555-3456",
    orders: [
      {
        orderId: 107,
        product: "Smartwatch",
        price: 250,
        date: "2024-06-12",
      },
      {
        orderId: 108,
        product: "Bluetooth Speaker",
        price: 100,
        date: "2024-07-18",
      },
    ],
  },
  {
    id: 5,
    name: "Emily White",
    email: "emily.white@example.com",
    age: 32,
    address: {
      street: "246 Birch St",
      city: "Houston",
      state: "TX",
      zip: "77002",
    },
    phone: "+1-555-7890",
    orders: [
      {
        orderId: 109,
        product: "Camera",
        price: 700,
        date: "2024-08-05",
      },
      {
        orderId: 110,
        product: "Tripod",
        price: 80,
        date: "2024-08-25",
      },
    ],
  },
  {
    id: 6,
    name: "David Green",
    email: "david.green@example.com",
    age: 27,
    address: {
      street: "789 Walnut St",
      city: "Seattle",
      state: "WA",
      zip: "98101",
    },
    phone: "+1-555-2345",
    orders: [
      {
        orderId: 111,
        product: "Desktop PC",
        price: 1500,
        date: "2024-09-10",
      },
      {
        orderId: 112,
        product: "Mechanical Keyboard",
        price: 120,
        date: "2024-09-30",
      },
    ],
  },
  {
    id: 1,
    name: "John Doe",
    email: "john.doe@example.com",
    age: 30,
    address: {
      street: "123 Main St",
      city: "New York",
      state: "NY",
      zip: "10001",
    },
    phone: "+1-555-1234",
    orders: [
      {
        orderId: 101,
        product: "Laptop",
        price: 1200,
        date: "2024-01-15",
      },
      {
        orderId: 102,
        product: "Smartphone",
        price: 800,
        date: "2024-02-10",
      },
    ],
  },
  {
    id: 2,
    name: "Jane Smith",
    email: "jane.smith@example.com",
    age: 28,
    address: {
      street: "456 Oak St",
      city: "San Francisco",
      state: "CA",
      zip: "94102",
    },
    phone: "+1-555-5678",
    orders: [
      {
        orderId: 103,
        product: "Tablet",
        price: 500,
        date: "2024-03-05",
      },
      {
        orderId: 104,
        product: "Wireless Headphones",
        price: 150,
        date: "2024-03-20",
      },
    ],
  },
  {
    id: 3,
    name: "Alice Johnson",
    email: "alice.johnson@example.com",
    age: 35,
    address: {
      street: "789 Pine St",
      city: "Chicago",
      state: "IL",
      zip: "60601",
    },
    phone: "+1-555-9012",
    orders: [
      {
        orderId: 105,
        product: "Gaming Console",
        price: 400,
        date: "2024-04-10",
      },
      {
        orderId: 106,
        product: "4K TV",
        price: 900,
        date: "2024-05-01",
      },
    ],
  },
  {
    id: 4,
    name: "Michael Brown",
    email: "michael.brown@example.com",
    age: 40,
    address: {
      street: "135 Maple St",
      city: "Los Angeles",
      state: "CA",
      zip: "90001",
    },
    phone: "+1-555-3456",
    orders: [
      {
        orderId: 107,
        product: "Smartwatch",
        price: 250,
        date: "2024-06-12",
      },
      {
        orderId: 108,
        product: "Bluetooth Speaker",
        price: 100,
        date: "2024-07-18",
      },
    ],
  },
  {
    id: 5,
    name: "Emily White",
    email: "emily.white@example.com",
    age: 32,
    address: {
      street: "246 Birch St",
      city: "Houston",
      state: "TX",
      zip: "77002",
    },
    phone: "+1-555-7890",
    orders: [
      {
        orderId: 109,
        product: "Camera",
        price: 700,
        date: "2024-08-05",
      },
      {
        orderId: 110,
        product: "Tripod",
        price: 80,
        date: "2024-08-25",
      },
    ],
  },
  {
    id: 6,
    name: "David Green",
    email: "david.green@example.com",
    age: 27,
    address: {
      street: "789 Walnut St",
      city: "Seattle",
      state: "WA",
      zip: "98101",
    },
    phone: "+1-555-2345",
    orders: [
      {
        orderId: 111,
        product: "Desktop PC",
        price: 1500,
        date: "2024-09-10",
      },
      {
        orderId: 112,
        product: "Mechanical Keyboard",
        price: 120,
        date: "2024-09-30",
      },
    ],
  },
  {
    id: 1,
    name: "John Doe",
    email: "john.doe@example.com",
    age: 30,
    address: {
      street: "123 Main St",
      city: "New York",
      state: "NY",
      zip: "10001",
    },
    phone: "+1-555-1234",
    orders: [
      {
        orderId: 101,
        product: "Laptop",
        price: 1200,
        date: "2024-01-15",
      },
      {
        orderId: 102,
        product: "Smartphone",
        price: 800,
        date: "2024-02-10",
      },
    ],
  },
  {
    id: 2,
    name: "Jane Smith",
    email: "jane.smith@example.com",
    age: 28,
    address: {
      street: "456 Oak St",
      city: "San Francisco",
      state: "CA",
      zip: "94102",
    },
    phone: "+1-555-5678",
    orders: [
      {
        orderId: 103,
        product: "Tablet",
        price: 500,
        date: "2024-03-05",
      },
      {
        orderId: 104,
        product: "Wireless Headphones",
        price: 150,
        date: "2024-03-20",
      },
    ],
  },
  {
    id: 3,
    name: "Alice Johnson",
    email: "alice.johnson@example.com",
    age: 35,
    address: {
      street: "789 Pine St",
      city: "Chicago",
      state: "IL",
      zip: "60601",
    },
    phone: "+1-555-9012",
    orders: [
      {
        orderId: 105,
        product: "Gaming Console",
        price: 400,
        date: "2024-04-10",
      },
      {
        orderId: 106,
        product: "4K TV",
        price: 900,
        date: "2024-05-01",
      },
    ],
  },
  {
    id: 4,
    name: "Michael Brown",
    email: "michael.brown@example.com",
    age: 40,
    address: {
      street: "135 Maple St",
      city: "Los Angeles",
      state: "CA",
      zip: "90001",
    },
    phone: "+1-555-3456",
    orders: [
      {
        orderId: 107,
        product: "Smartwatch",
        price: 250,
        date: "2024-06-12",
      },
      {
        orderId: 108,
        product: "Bluetooth Speaker",
        price: 100,
        date: "2024-07-18",
      },
    ],
  },
  {
    id: 5,
    name: "Emily White",
    email: "emily.white@example.com",
    age: 32,
    address: {
      street: "246 Birch St",
      city: "Houston",
      state: "TX",
      zip: "77002",
    },
    phone: "+1-555-7890",
    orders: [
      {
        orderId: 109,
        product: "Camera",
        price: 700,
        date: "2024-08-05",
      },
      {
        orderId: 110,
        product: "Tripod",
        price: 80,
        date: "2024-08-25",
      },
    ],
  },
  {
    id: 6,
    name: "David Green",
    email: "david.green@example.com",
    age: 27,
    address: {
      street: "789 Walnut St",
      city: "Seattle",
      state: "WA",
      zip: "98101",
    },
    phone: "+1-555-2345",
    orders: [
      {
        orderId: 111,
        product: "Desktop PC",
        price: 1500,
        date: "2024-09-10",
      },
      {
        orderId: 112,
        product: "Mechanical Keyboard",
        price: 120,
        date: "2024-09-30",
      },
    ],
  },
  {
    id: 1,
    name: "John Doe",
    email: "john.doe@example.com",
    age: 30,
    address: {
      street: "123 Main St",
      city: "New York",
      state: "NY",
      zip: "10001",
    },
    phone: "+1-555-1234",
    orders: [
      {
        orderId: 101,
        product: "Laptop",
        price: 1200,
        date: "2024-01-15",
      },
      {
        orderId: 102,
        product: "Smartphone",
        price: 800,
        date: "2024-02-10",
      },
    ],
  },
  {
    id: 2,
    name: "Jane Smith",
    email: "jane.smith@example.com",
    age: 28,
    address: {
      street: "456 Oak St",
      city: "San Francisco",
      state: "CA",
      zip: "94102",
    },
    phone: "+1-555-5678",
    orders: [
      {
        orderId: 103,
        product: "Tablet",
        price: 500,
        date: "2024-03-05",
      },
      {
        orderId: 104,
        product: "Wireless Headphones",
        price: 150,
        date: "2024-03-20",
      },
    ],
  },
  {
    id: 3,
    name: "Alice Johnson",
    email: "alice.johnson@example.com",
    age: 35,
    address: {
      street: "789 Pine St",
      city: "Chicago",
      state: "IL",
      zip: "60601",
    },
    phone: "+1-555-9012",
    orders: [
      {
        orderId: 105,
        product: "Gaming Console",
        price: 400,
        date: "2024-04-10",
      },
      {
        orderId: 106,
        product: "4K TV",
        price: 900,
        date: "2024-05-01",
      },
    ],
  },
  {
    id: 4,
    name: "Michael Brown",
    email: "michael.brown@example.com",
    age: 40,
    address: {
      street: "135 Maple St",
      city: "Los Angeles",
      state: "CA",
      zip: "90001",
    },
    phone: "+1-555-3456",
    orders: [
      {
        orderId: 107,
        product: "Smartwatch",
        price: 250,
        date: "2024-06-12",
      },
      {
        orderId: 108,
        product: "Bluetooth Speaker",
        price: 100,
        date: "2024-07-18",
      },
    ],
  },
  {
    id: 5,
    name: "Emily White",
    email: "emily.white@example.com",
    age: 32,
    address: {
      street: "246 Birch St",
      city: "Houston",
      state: "TX",
      zip: "77002",
    },
    phone: "+1-555-7890",
    orders: [
      {
        orderId: 109,
        product: "Camera",
        price: 700,
        date: "2024-08-05",
      },
      {
        orderId: 110,
        product: "Tripod",
        price: 80,
        date: "2024-08-25",
      },
    ],
  },
  {
    id: 6,
    name: "David Green",
    email: "david.green@example.com",
    age: 27,
    address: {
      street: "789 Walnut St",
      city: "Seattle",
      state: "WA",
      zip: "98101",
    },
    phone: "+1-555-2345",
    orders: [
      {
        orderId: 111,
        product: "Desktop PC",
        price: 1500,
        date: "2024-09-10",
      },
      {
        orderId: 112,
        product: "Mechanical Keyboard",
        price: 120,
        date: "2024-09-30",
      },
    ],
  },
  {
    id: 1,
    name: "John Doe",
    email: "john.doe@example.com",
    age: 30,
    address: {
      street: "123 Main St",
      city: "New York",
      state: "NY",
      zip: "10001",
    },
    phone: "+1-555-1234",
    orders: [
      {
        orderId: 101,
        product: "Laptop",
        price: 1200,
        date: "2024-01-15",
      },
      {
        orderId: 102,
        product: "Smartphone",
        price: 800,
        date: "2024-02-10",
      },
    ],
  },
  {
    id: 2,
    name: "Jane Smith",
    email: "jane.smith@example.com",
    age: 28,
    address: {
      street: "456 Oak St",
      city: "San Francisco",
      state: "CA",
      zip: "94102",
    },
    phone: "+1-555-5678",
    orders: [
      {
        orderId: 103,
        product: "Tablet",
        price: 500,
        date: "2024-03-05",
      },
      {
        orderId: 104,
        product: "Wireless Headphones",
        price: 150,
        date: "2024-03-20",
      },
    ],
  },
  {
    id: 3,
    name: "Alice Johnson",
    email: "alice.johnson@example.com",
    age: 35,
    address: {
      street: "789 Pine St",
      city: "Chicago",
      state: "IL",
      zip: "60601",
    },
    phone: "+1-555-9012",
    orders: [
      {
        orderId: 105,
        product: "Gaming Console",
        price: 400,
        date: "2024-04-10",
      },
      {
        orderId: 106,
        product: "4K TV",
        price: 900,
        date: "2024-05-01",
      },
    ],
  },
  {
    id: 4,
    name: "Michael Brown",
    email: "michael.brown@example.com",
    age: 40,
    address: {
      street: "135 Maple St",
      city: "Los Angeles",
      state: "CA",
      zip: "90001",
    },
    phone: "+1-555-3456",
    orders: [
      {
        orderId: 107,
        product: "Smartwatch",
        price: 250,
        date: "2024-06-12",
      },
      {
        orderId: 108,
        product: "Bluetooth Speaker",
        price: 100,
        date: "2024-07-18",
      },
    ],
  },
  {
    id: 5,
    name: "Emily White",
    email: "emily.white@example.com",
    age: 32,
    address: {
      street: "246 Birch St",
      city: "Houston",
      state: "TX",
      zip: "77002",
    },
    phone: "+1-555-7890",
    orders: [
      {
        orderId: 109,
        product: "Camera",
        price: 700,
        date: "2024-08-05",
      },
      {
        orderId: 110,
        product: "Tripod",
        price: 80,
        date: "2024-08-25",
      },
    ],
  },
  {
    id: 6,
    name: "David Green",
    email: "david.green@example.com",
    age: 27,
    address: {
      street: "789 Walnut St",
      city: "Seattle",
      state: "WA",
      zip: "98101",
    },
    phone: "+1-555-2345",
    orders: [
      {
        orderId: 111,
        product: "Desktop PC",
        price: 1500,
        date: "2024-09-10",
      },
      {
        orderId: 112,
        product: "Mechanical Keyboard",
        price: 120,
        date: "2024-09-30",
      },
    ],
  },
  {
    id: 1,
    name: "John Doe",
    email: "john.doe@example.com",
    age: 30,
    address: {
      street: "123 Main St",
      city: "New York",
      state: "NY",
      zip: "10001",
    },
    phone: "+1-555-1234",
    orders: [
      {
        orderId: 101,
        product: "Laptop",
        price: 1200,
        date: "2024-01-15",
      },
      {
        orderId: 102,
        product: "Smartphone",
        price: 800,
        date: "2024-02-10",
      },
    ],
  },
  {
    id: 2,
    name: "Jane Smith",
    email: "jane.smith@example.com",
    age: 28,
    address: {
      street: "456 Oak St",
      city: "San Francisco",
      state: "CA",
      zip: "94102",
    },
    phone: "+1-555-5678",
    orders: [
      {
        orderId: 103,
        product: "Tablet",
        price: 500,
        date: "2024-03-05",
      },
      {
        orderId: 104,
        product: "Wireless Headphones",
        price: 150,
        date: "2024-03-20",
      },
    ],
  },
  {
    id: 3,
    name: "Alice Johnson",
    email: "alice.johnson@example.com",
    age: 35,
    address: {
      street: "789 Pine St",
      city: "Chicago",
      state: "IL",
      zip: "60601",
    },
    phone: "+1-555-9012",
    orders: [
      {
        orderId: 105,
        product: "Gaming Console",
        price: 400,
        date: "2024-04-10",
      },
      {
        orderId: 106,
        product: "4K TV",
        price: 900,
        date: "2024-05-01",
      },
    ],
  },
  {
    id: 4,
    name: "Michael Brown",
    email: "michael.brown@example.com",
    age: 40,
    address: {
      street: "135 Maple St",
      city: "Los Angeles",
      state: "CA",
      zip: "90001",
    },
    phone: "+1-555-3456",
    orders: [
      {
        orderId: 107,
        product: "Smartwatch",
        price: 250,
        date: "2024-06-12",
      },
      {
        orderId: 108,
        product: "Bluetooth Speaker",
        price: 100,
        date: "2024-07-18",
      },
    ],
  },
  {
    id: 5,
    name: "Emily White",
    email: "emily.white@example.com",
    age: 32,
    address: {
      street: "246 Birch St",
      city: "Houston",
      state: "TX",
      zip: "77002",
    },
    phone: "+1-555-7890",
    orders: [
      {
        orderId: 109,
        product: "Camera",
        price: 700,
        date: "2024-08-05",
      },
      {
        orderId: 110,
        product: "Tripod",
        price: 80,
        date: "2024-08-25",
      },
    ],
  },
  {
    id: 6,
    name: "David Green",
    email: "david.green@example.com",
    age: 27,
    address: {
      street: "789 Walnut St",
      city: "Seattle",
      state: "WA",
      zip: "98101",
    },
    phone: "+1-555-2345",
    orders: [
      {
        orderId: 111,
        product: "Desktop PC",
        price: 1500,
        date: "2024-09-10",
      },
      {
        orderId: 112,
        product: "Mechanical Keyboard",
        price: 120,
        date: "2024-09-30",
      },
    ],
  },
  {
    id: 1,
    name: "John Doe",
    email: "john.doe@example.com",
    age: 30,
    address: {
      street: "123 Main St",
      city: "New York",
      state: "NY",
      zip: "10001",
    },
    phone: "+1-555-1234",
    orders: [
      {
        orderId: 101,
        product: "Laptop",
        price: 1200,
        date: "2024-01-15",
      },
      {
        orderId: 102,
        product: "Smartphone",
        price: 800,
        date: "2024-02-10",
      },
    ],
  },
  {
    id: 2,
    name: "Jane Smith",
    email: "jane.smith@example.com",
    age: 28,
    address: {
      street: "456 Oak St",
      city: "San Francisco",
      state: "CA",
      zip: "94102",
    },
    phone: "+1-555-5678",
    orders: [
      {
        orderId: 103,
        product: "Tablet",
        price: 500,
        date: "2024-03-05",
      },
      {
        orderId: 104,
        product: "Wireless Headphones",
        price: 150,
        date: "2024-03-20",
      },
    ],
  },
  {
    id: 3,
    name: "Alice Johnson",
    email: "alice.johnson@example.com",
    age: 35,
    address: {
      street: "789 Pine St",
      city: "Chicago",
      state: "IL",
      zip: "60601",
    },
    phone: "+1-555-9012",
    orders: [
      {
        orderId: 105,
        product: "Gaming Console",
        price: 400,
        date: "2024-04-10",
      },
      {
        orderId: 106,
        product: "4K TV",
        price: 900,
        date: "2024-05-01",
      },
    ],
  },
  {
    id: 4,
    name: "Michael Brown",
    email: "michael.brown@example.com",
    age: 40,
    address: {
      street: "135 Maple St",
      city: "Los Angeles",
      state: "CA",
      zip: "90001",
    },
    phone: "+1-555-3456",
    orders: [
      {
        orderId: 107,
        product: "Smartwatch",
        price: 250,
        date: "2024-06-12",
      },
      {
        orderId: 108,
        product: "Bluetooth Speaker",
        price: 100,
        date: "2024-07-18",
      },
    ],
  },
  {
    id: 5,
    name: "Emily White",
    email: "emily.white@example.com",
    age: 32,
    address: {
      street: "246 Birch St",
      city: "Houston",
      state: "TX",
      zip: "77002",
    },
    phone: "+1-555-7890",
    orders: [
      {
        orderId: 109,
        product: "Camera",
        price: 700,
        date: "2024-08-05",
      },
      {
        orderId: 110,
        product: "Tripod",
        price: 80,
        date: "2024-08-25",
      },
    ],
  },
  {
    id: 6,
    name: "David Green",
    email: "david.green@example.com",
    age: 27,
    address: {
      street: "789 Walnut St",
      city: "Seattle",
      state: "WA",
      zip: "98101",
    },
    phone: "+1-555-2345",
    orders: [
      {
        orderId: 111,
        product: "Desktop PC",
        price: 1500,
        date: "2024-09-10",
      },
      {
        orderId: 112,
        product: "Mechanical Keyboard",
        price: 120,
        date: "2024-09-30",
      },
    ],
  },
  {
    id: 1,
    name: "John Doe",
    email: "john.doe@example.com",
    age: 30,
    address: {
      street: "123 Main St",
      city: "New York",
      state: "NY",
      zip: "10001",
    },
    phone: "+1-555-1234",
    orders: [
      {
        orderId: 101,
        product: "Laptop",
        price: 1200,
        date: "2024-01-15",
      },
      {
        orderId: 102,
        product: "Smartphone",
        price: 800,
        date: "2024-02-10",
      },
    ],
  },
  {
    id: 2,
    name: "Jane Smith",
    email: "jane.smith@example.com",
    age: 28,
    address: {
      street: "456 Oak St",
      city: "San Francisco",
      state: "CA",
      zip: "94102",
    },
    phone: "+1-555-5678",
    orders: [
      {
        orderId: 103,
        product: "Tablet",
        price: 500,
        date: "2024-03-05",
      },
      {
        orderId: 104,
        product: "Wireless Headphones",
        price: 150,
        date: "2024-03-20",
      },
    ],
  },
  {
    id: 3,
    name: "Alice Johnson",
    email: "alice.johnson@example.com",
    age: 35,
    address: {
      street: "789 Pine St",
      city: "Chicago",
      state: "IL",
      zip: "60601",
    },
    phone: "+1-555-9012",
    orders: [
      {
        orderId: 105,
        product: "Gaming Console",
        price: 400,
        date: "2024-04-10",
      },
      {
        orderId: 106,
        product: "4K TV",
        price: 900,
        date: "2024-05-01",
      },
    ],
  },
  {
    id: 4,
    name: "Michael Brown",
    email: "michael.brown@example.com",
    age: 40,
    address: {
      street: "135 Maple St",
      city: "Los Angeles",
      state: "CA",
      zip: "90001",
    },
    phone: "+1-555-3456",
    orders: [
      {
        orderId: 107,
        product: "Smartwatch",
        price: 250,
        date: "2024-06-12",
      },
      {
        orderId: 108,
        product: "Bluetooth Speaker",
        price: 100,
        date: "2024-07-18",
      },
    ],
  },
  {
    id: 5,
    name: "Emily White",
    email: "emily.white@example.com",
    age: 32,
    address: {
      street: "246 Birch St",
      city: "Houston",
      state: "TX",
      zip: "77002",
    },
    phone: "+1-555-7890",
    orders: [
      {
        orderId: 109,
        product: "Camera",
        price: 700,
        date: "2024-08-05",
      },
      {
        orderId: 110,
        product: "Tripod",
        price: 80,
        date: "2024-08-25",
      },
    ],
  },
  {
    id: 6,
    name: "David Green",
    email: "david.green@example.com",
    age: 27,
    address: {
      street: "789 Walnut St",
      city: "Seattle",
      state: "WA",
      zip: "98101",
    },
    phone: "+1-555-2345",
    orders: [
      {
        orderId: 111,
        product: "Desktop PC",
        price: 1500,
        date: "2024-09-10",
      },
      {
        orderId: 112,
        product: "Mechanical Keyboard",
        price: 120,
        date: "2024-09-30",
      },
    ],
  },
  {
    id: 1,
    name: "John Doe",
    email: "john.doe@example.com",
    age: 30,
    address: {
      street: "123 Main St",
      city: "New York",
      state: "NY",
      zip: "10001",
    },
    phone: "+1-555-1234",
    orders: [
      {
        orderId: 101,
        product: "Laptop",
        price: 1200,
        date: "2024-01-15",
      },
      {
        orderId: 102,
        product: "Smartphone",
        price: 800,
        date: "2024-02-10",
      },
    ],
  },
  {
    id: 2,
    name: "Jane Smith",
    email: "jane.smith@example.com",
    age: 28,
    address: {
      street: "456 Oak St",
      city: "San Francisco",
      state: "CA",
      zip: "94102",
    },
    phone: "+1-555-5678",
    orders: [
      {
        orderId: 103,
        product: "Tablet",
        price: 500,
        date: "2024-03-05",
      },
      {
        orderId: 104,
        product: "Wireless Headphones",
        price: 150,
        date: "2024-03-20",
      },
    ],
  },
  {
    id: 3,
    name: "Alice Johnson",
    email: "alice.johnson@example.com",
    age: 35,
    address: {
      street: "789 Pine St",
      city: "Chicago",
      state: "IL",
      zip: "60601",
    },
    phone: "+1-555-9012",
    orders: [
      {
        orderId: 105,
        product: "Gaming Console",
        price: 400,
        date: "2024-04-10",
      },
      {
        orderId: 106,
        product: "4K TV",
        price: 900,
        date: "2024-05-01",
      },
    ],
  },
  {
    id: 4,
    name: "Michael Brown",
    email: "michael.brown@example.com",
    age: 40,
    address: {
      street: "135 Maple St",
      city: "Los Angeles",
      state: "CA",
      zip: "90001",
    },
    phone: "+1-555-3456",
    orders: [
      {
        orderId: 107,
        product: "Smartwatch",
        price: 250,
        date: "2024-06-12",
      },
      {
        orderId: 108,
        product: "Bluetooth Speaker",
        price: 100,
        date: "2024-07-18",
      },
    ],
  },
  {
    id: 5,
    name: "Emily White",
    email: "emily.white@example.com",
    age: 32,
    address: {
      street: "246 Birch St",
      city: "Houston",
      state: "TX",
      zip: "77002",
    },
    phone: "+1-555-7890",
    orders: [
      {
        orderId: 109,
        product: "Camera",
        price: 700,
        date: "2024-08-05",
      },
      {
        orderId: 110,
        product: "Tripod",
        price: 80,
        date: "2024-08-25",
      },
    ],
  },
  {
    id: 6,
    name: "David Green",
    email: "david.green@example.com",
    age: 27,
    address: {
      street: "789 Walnut St",
      city: "Seattle",
      state: "WA",
      zip: "98101",
    },
    phone: "+1-555-2345",
    orders: [
      {
        orderId: 111,
        product: "Desktop PC",
        price: 1500,
        date: "2024-09-10",
      },
      {
        orderId: 112,
        product: "Mechanical Keyboard",
        price: 120,
        date: "2024-09-30",
      },
    ],
  },
  {
    id: 1,
    name: "John Doe",
    email: "john.doe@example.com",
    age: 30,
    address: {
      street: "123 Main St",
      city: "New York",
      state: "NY",
      zip: "10001",
    },
    phone: "+1-555-1234",
    orders: [
      {
        orderId: 101,
        product: "Laptop",
        price: 1200,
        date: "2024-01-15",
      },
      {
        orderId: 102,
        product: "Smartphone",
        price: 800,
        date: "2024-02-10",
      },
    ],
  },
  {
    id: 2,
    name: "Jane Smith",
    email: "jane.smith@example.com",
    age: 28,
    address: {
      street: "456 Oak St",
      city: "San Francisco",
      state: "CA",
      zip: "94102",
    },
    phone: "+1-555-5678",
    orders: [
      {
        orderId: 103,
        product: "Tablet",
        price: 500,
        date: "2024-03-05",
      },
      {
        orderId: 104,
        product: "Wireless Headphones",
        price: 150,
        date: "2024-03-20",
      },
    ],
  },
  {
    id: 3,
    name: "Alice Johnson",
    email: "alice.johnson@example.com",
    age: 35,
    address: {
      street: "789 Pine St",
      city: "Chicago",
      state: "IL",
      zip: "60601",
    },
    phone: "+1-555-9012",
    orders: [
      {
        orderId: 105,
        product: "Gaming Console",
        price: 400,
        date: "2024-04-10",
      },
      {
        orderId: 106,
        product: "4K TV",
        price: 900,
        date: "2024-05-01",
      },
    ],
  },
  {
    id: 4,
    name: "Michael Brown",
    email: "michael.brown@example.com",
    age: 40,
    address: {
      street: "135 Maple St",
      city: "Los Angeles",
      state: "CA",
      zip: "90001",
    },
    phone: "+1-555-3456",
    orders: [
      {
        orderId: 107,
        product: "Smartwatch",
        price: 250,
        date: "2024-06-12",
      },
      {
        orderId: 108,
        product: "Bluetooth Speaker",
        price: 100,
        date: "2024-07-18",
      },
    ],
  },
  {
    id: 5,
    name: "Emily White",
    email: "emily.white@example.com",
    age: 32,
    address: {
      street: "246 Birch St",
      city: "Houston",
      state: "TX",
      zip: "77002",
    },
    phone: "+1-555-7890",
    orders: [
      {
        orderId: 109,
        product: "Camera",
        price: 700,
        date: "2024-08-05",
      },
      {
        orderId: 110,
        product: "Tripod",
        price: 80,
        date: "2024-08-25",
      },
    ],
  },
  {
    id: 6,
    name: "David Green",
    email: "david.green@example.com",
    age: 27,
    address: {
      street: "789 Walnut St",
      city: "Seattle",
      state: "WA",
      zip: "98101",
    },
    phone: "+1-555-2345",
    orders: [
      {
        orderId: 111,
        product: "Desktop PC",
        price: 1500,
        date: "2024-09-10",
      },
      {
        orderId: 112,
        product: "Mechanical Keyboard",
        price: 120,
        date: "2024-09-30",
      },
    ],
  },
  {
    id: 1,
    name: "John Doe",
    email: "john.doe@example.com",
    age: 30,
    address: {
      street: "123 Main St",
      city: "New York",
      state: "NY",
      zip: "10001",
    },
    phone: "+1-555-1234",
    orders: [
      {
        orderId: 101,
        product: "Laptop",
        price: 1200,
        date: "2024-01-15",
      },
      {
        orderId: 102,
        product: "Smartphone",
        price: 800,
        date: "2024-02-10",
      },
    ],
  },
  {
    id: 2,
    name: "Jane Smith",
    email: "jane.smith@example.com",
    age: 28,
    address: {
      street: "456 Oak St",
      city: "San Francisco",
      state: "CA",
      zip: "94102",
    },
    phone: "+1-555-5678",
    orders: [
      {
        orderId: 103,
        product: "Tablet",
        price: 500,
        date: "2024-03-05",
      },
      {
        orderId: 104,
        product: "Wireless Headphones",
        price: 150,
        date: "2024-03-20",
      },
    ],
  },
  {
    id: 3,
    name: "Alice Johnson",
    email: "alice.johnson@example.com",
    age: 35,
    address: {
      street: "789 Pine St",
      city: "Chicago",
      state: "IL",
      zip: "60601",
    },
    phone: "+1-555-9012",
    orders: [
      {
        orderId: 105,
        product: "Gaming Console",
        price: 400,
        date: "2024-04-10",
      },
      {
        orderId: 106,
        product: "4K TV",
        price: 900,
        date: "2024-05-01",
      },
    ],
  },
  {
    id: 4,
    name: "Michael Brown",
    email: "michael.brown@example.com",
    age: 40,
    address: {
      street: "135 Maple St",
      city: "Los Angeles",
      state: "CA",
      zip: "90001",
    },
    phone: "+1-555-3456",
    orders: [
      {
        orderId: 107,
        product: "Smartwatch",
        price: 250,
        date: "2024-06-12",
      },
      {
        orderId: 108,
        product: "Bluetooth Speaker",
        price: 100,
        date: "2024-07-18",
      },
    ],
  },
  {
    id: 5,
    name: "Emily White",
    email: "emily.white@example.com",
    age: 32,
    address: {
      street: "246 Birch St",
      city: "Houston",
      state: "TX",
      zip: "77002",
    },
    phone: "+1-555-7890",
    orders: [
      {
        orderId: 109,
        product: "Camera",
        price: 700,
        date: "2024-08-05",
      },
      {
        orderId: 110,
        product: "Tripod",
        price: 80,
        date: "2024-08-25",
      },
    ],
  },
  {
    id: 6,
    name: "David Green",
    email: "david.green@example.com",
    age: 27,
    address: {
      street: "789 Walnut St",
      city: "Seattle",
      state: "WA",
      zip: "98101",
    },
    phone: "+1-555-2345",
    orders: [
      {
        orderId: 111,
        product: "Desktop PC",
        price: 1500,
        date: "2024-09-10",
      },
      {
        orderId: 112,
        product: "Mechanical Keyboard",
        price: 120,
        date: "2024-09-30",
      },
    ],
  },
  {
    id: 1,
    name: "John Doe",
    email: "john.doe@example.com",
    age: 30,
    address: {
      street: "123 Main St",
      city: "New York",
      state: "NY",
      zip: "10001",
    },
    phone: "+1-555-1234",
    orders: [
      {
        orderId: 101,
        product: "Laptop",
        price: 1200,
        date: "2024-01-15",
      },
      {
        orderId: 102,
        product: "Smartphone",
        price: 800,
        date: "2024-02-10",
      },
    ],
  },
  {
    id: 2,
    name: "Jane Smith",
    email: "jane.smith@example.com",
    age: 28,
    address: {
      street: "456 Oak St",
      city: "San Francisco",
      state: "CA",
      zip: "94102",
    },
    phone: "+1-555-5678",
    orders: [
      {
        orderId: 103,
        product: "Tablet",
        price: 500,
        date: "2024-03-05",
      },
      {
        orderId: 104,
        product: "Wireless Headphones",
        price: 150,
        date: "2024-03-20",
      },
    ],
  },
  {
    id: 3,
    name: "Alice Johnson",
    email: "alice.johnson@example.com",
    age: 35,
    address: {
      street: "789 Pine St",
      city: "Chicago",
      state: "IL",
      zip: "60601",
    },
    phone: "+1-555-9012",
    orders: [
      {
        orderId: 105,
        product: "Gaming Console",
        price: 400,
        date: "2024-04-10",
      },
      {
        orderId: 106,
        product: "4K TV",
        price: 900,
        date: "2024-05-01",
      },
    ],
  },
  {
    id: 4,
    name: "Michael Brown",
    email: "michael.brown@example.com",
    age: 40,
    address: {
      street: "135 Maple St",
      city: "Los Angeles",
      state: "CA",
      zip: "90001",
    },
    phone: "+1-555-3456",
    orders: [
      {
        orderId: 107,
        product: "Smartwatch",
        price: 250,
        date: "2024-06-12",
      },
      {
        orderId: 108,
        product: "Bluetooth Speaker",
        price: 100,
        date: "2024-07-18",
      },
    ],
  },
  {
    id: 5,
    name: "Emily White",
    email: "emily.white@example.com",
    age: 32,
    address: {
      street: "246 Birch St",
      city: "Houston",
      state: "TX",
      zip: "77002",
    },
    phone: "+1-555-7890",
    orders: [
      {
        orderId: 109,
        product: "Camera",
        price: 700,
        date: "2024-08-05",
      },
      {
        orderId: 110,
        product: "Tripod",
        price: 80,
        date: "2024-08-25",
      },
    ],
  },
  {
    id: 6,
    name: "David Green",
    email: "david.green@example.com",
    age: 27,
    address: {
      street: "789 Walnut St",
      city: "Seattle",
      state: "WA",
      zip: "98101",
    },
    phone: "+1-555-2345",
    orders: [
      {
        orderId: 111,
        product: "Desktop PC",
        price: 1500,
        date: "2024-09-10",
      },
      {
        orderId: 112,
        product: "Mechanical Keyboard",
        price: 120,
        date: "2024-09-30",
      },
    ],
  },
  {
    id: 1,
    name: "John Doe",
    email: "john.doe@example.com",
    age: 30,
    address: {
      street: "123 Main St",
      city: "New York",
      state: "NY",
      zip: "10001",
    },
    phone: "+1-555-1234",
    orders: [
      {
        orderId: 101,
        product: "Laptop",
        price: 1200,
        date: "2024-01-15",
      },
      {
        orderId: 102,
        product: "Smartphone",
        price: 800,
        date: "2024-02-10",
      },
    ],
  },
  {
    id: 2,
    name: "Jane Smith",
    email: "jane.smith@example.com",
    age: 28,
    address: {
      street: "456 Oak St",
      city: "San Francisco",
      state: "CA",
      zip: "94102",
    },
    phone: "+1-555-5678",
    orders: [
      {
        orderId: 103,
        product: "Tablet",
        price: 500,
        date: "2024-03-05",
      },
      {
        orderId: 104,
        product: "Wireless Headphones",
        price: 150,
        date: "2024-03-20",
      },
    ],
  },
  {
    id: 3,
    name: "Alice Johnson",
    email: "alice.johnson@example.com",
    age: 35,
    address: {
      street: "789 Pine St",
      city: "Chicago",
      state: "IL",
      zip: "60601",
    },
    phone: "+1-555-9012",
    orders: [
      {
        orderId: 105,
        product: "Gaming Console",
        price: 400,
        date: "2024-04-10",
      },
      {
        orderId: 106,
        product: "4K TV",
        price: 900,
        date: "2024-05-01",
      },
    ],
  },
  {
    id: 4,
    name: "Michael Brown",
    email: "michael.brown@example.com",
    age: 40,
    address: {
      street: "135 Maple St",
      city: "Los Angeles",
      state: "CA",
      zip: "90001",
    },
    phone: "+1-555-3456",
    orders: [
      {
        orderId: 107,
        product: "Smartwatch",
        price: 250,
        date: "2024-06-12",
      },
      {
        orderId: 108,
        product: "Bluetooth Speaker",
        price: 100,
        date: "2024-07-18",
      },
    ],
  },
  {
    id: 5,
    name: "Emily White",
    email: "emily.white@example.com",
    age: 32,
    address: {
      street: "246 Birch St",
      city: "Houston",
      state: "TX",
      zip: "77002",
    },
    phone: "+1-555-7890",
    orders: [
      {
        orderId: 109,
        product: "Camera",
        price: 700,
        date: "2024-08-05",
      },
      {
        orderId: 110,
        product: "Tripod",
        price: 80,
        date: "2024-08-25",
      },
    ],
  },
  {
    id: 6,
    name: "David Green",
    email: "david.green@example.com",
    age: 27,
    address: {
      street: "789 Walnut St",
      city: "Seattle",
      state: "WA",
      zip: "98101",
    },
    phone: "+1-555-2345",
    orders: [
      {
        orderId: 111,
        product: "Desktop PC",
        price: 1500,
        date: "2024-09-10",
      },
      {
        orderId: 112,
        product: "Mechanical Keyboard",
        price: 120,
        date: "2024-09-30",
      },
    ],
  },
  {
    id: 1,
    name: "John Doe",
    email: "john.doe@example.com",
    age: 30,
    address: {
      street: "123 Main St",
      city: "New York",
      state: "NY",
      zip: "10001",
    },
    phone: "+1-555-1234",
    orders: [
      {
        orderId: 101,
        product: "Laptop",
        price: 1200,
        date: "2024-01-15",
      },
      {
        orderId: 102,
        product: "Smartphone",
        price: 800,
        date: "2024-02-10",
      },
    ],
  },
  {
    id: 2,
    name: "Jane Smith",
    email: "jane.smith@example.com",
    age: 28,
    address: {
      street: "456 Oak St",
      city: "San Francisco",
      state: "CA",
      zip: "94102",
    },
    phone: "+1-555-5678",
    orders: [
      {
        orderId: 103,
        product: "Tablet",
        price: 500,
        date: "2024-03-05",
      },
      {
        orderId: 104,
        product: "Wireless Headphones",
        price: 150,
        date: "2024-03-20",
      },
    ],
  },
  {
    id: 3,
    name: "Alice Johnson",
    email: "alice.johnson@example.com",
    age: 35,
    address: {
      street: "789 Pine St",
      city: "Chicago",
      state: "IL",
      zip: "60601",
    },
    phone: "+1-555-9012",
    orders: [
      {
        orderId: 105,
        product: "Gaming Console",
        price: 400,
        date: "2024-04-10",
      },
      {
        orderId: 106,
        product: "4K TV",
        price: 900,
        date: "2024-05-01",
      },
    ],
  },
  {
    id: 4,
    name: "Michael Brown",
    email: "michael.brown@example.com",
    age: 40,
    address: {
      street: "135 Maple St",
      city: "Los Angeles",
      state: "CA",
      zip: "90001",
    },
    phone: "+1-555-3456",
    orders: [
      {
        orderId: 107,
        product: "Smartwatch",
        price: 250,
        date: "2024-06-12",
      },
      {
        orderId: 108,
        product: "Bluetooth Speaker",
        price: 100,
        date: "2024-07-18",
      },
    ],
  },
  {
    id: 5,
    name: "Emily White",
    email: "emily.white@example.com",
    age: 32,
    address: {
      street: "246 Birch St",
      city: "Houston",
      state: "TX",
      zip: "77002",
    },
    phone: "+1-555-7890",
    orders: [
      {
        orderId: 109,
        product: "Camera",
        price: 700,
        date: "2024-08-05",
      },
      {
        orderId: 110,
        product: "Tripod",
        price: 80,
        date: "2024-08-25",
      },
    ],
  },
  {
    id: 6,
    name: "David Green",
    email: "david.green@example.com",
    age: 27,
    address: {
      street: "789 Walnut St",
      city: "Seattle",
      state: "WA",
      zip: "98101",
    },
    phone: "+1-555-2345",
    orders: [
      {
        orderId: 111,
        product: "Desktop PC",
        price: 1500,
        date: "2024-09-10",
      },
      {
        orderId: 112,
        product: "Mechanical Keyboard",
        price: 120,
        date: "2024-09-30",
      },
    ],
  },
  {
    id: 1,
    name: "John Doe",
    email: "john.doe@example.com",
    age: 30,
    address: {
      street: "123 Main St",
      city: "New York",
      state: "NY",
      zip: "10001",
    },
    phone: "+1-555-1234",
    orders: [
      {
        orderId: 101,
        product: "Laptop",
        price: 1200,
        date: "2024-01-15",
      },
      {
        orderId: 102,
        product: "Smartphone",
        price: 800,
        date: "2024-02-10",
      },
    ],
  },
  {
    id: 2,
    name: "Jane Smith",
    email: "jane.smith@example.com",
    age: 28,
    address: {
      street: "456 Oak St",
      city: "San Francisco",
      state: "CA",
      zip: "94102",
    },
    phone: "+1-555-5678",
    orders: [
      {
        orderId: 103,
        product: "Tablet",
        price: 500,
        date: "2024-03-05",
      },
      {
        orderId: 104,
        product: "Wireless Headphones",
        price: 150,
        date: "2024-03-20",
      },
    ],
  },
  {
    id: 3,
    name: "Alice Johnson",
    email: "alice.johnson@example.com",
    age: 35,
    address: {
      street: "789 Pine St",
      city: "Chicago",
      state: "IL",
      zip: "60601",
    },
    phone: "+1-555-9012",
    orders: [
      {
        orderId: 105,
        product: "Gaming Console",
        price: 400,
        date: "2024-04-10",
      },
      {
        orderId: 106,
        product: "4K TV",
        price: 900,
        date: "2024-05-01",
      },
    ],
  },
  {
    id: 4,
    name: "Michael Brown",
    email: "michael.brown@example.com",
    age: 40,
    address: {
      street: "135 Maple St",
      city: "Los Angeles",
      state: "CA",
      zip: "90001",
    },
    phone: "+1-555-3456",
    orders: [
      {
        orderId: 107,
        product: "Smartwatch",
        price: 250,
        date: "2024-06-12",
      },
      {
        orderId: 108,
        product: "Bluetooth Speaker",
        price: 100,
        date: "2024-07-18",
      },
    ],
  },
  {
    id: 5,
    name: "Emily White",
    email: "emily.white@example.com",
    age: 32,
    address: {
      street: "246 Birch St",
      city: "Houston",
      state: "TX",
      zip: "77002",
    },
    phone: "+1-555-7890",
    orders: [
      {
        orderId: 109,
        product: "Camera",
        price: 700,
        date: "2024-08-05",
      },
      {
        orderId: 110,
        product: "Tripod",
        price: 80,
        date: "2024-08-25",
      },
    ],
  },
  {
    id: 6,
    name: "David Green",
    email: "david.green@example.com",
    age: 27,
    address: {
      street: "789 Walnut St",
      city: "Seattle",
      state: "WA",
      zip: "98101",
    },
    phone: "+1-555-2345",
    orders: [
      {
        orderId: 111,
        product: "Desktop PC",
        price: 1500,
        date: "2024-09-10",
      },
      {
        orderId: 112,
        product: "Mechanical Keyboard",
        price: 120,
        date: "2024-09-30",
      },
    ],
  },
  {
    id: 1,
    name: "John Doe",
    email: "john.doe@example.com",
    age: 30,
    address: {
      street: "123 Main St",
      city: "New York",
      state: "NY",
      zip: "10001",
    },
    phone: "+1-555-1234",
    orders: [
      {
        orderId: 101,
        product: "Laptop",
        price: 1200,
        date: "2024-01-15",
      },
      {
        orderId: 102,
        product: "Smartphone",
        price: 800,
        date: "2024-02-10",
      },
    ],
  },
  {
    id: 2,
    name: "Jane Smith",
    email: "jane.smith@example.com",
    age: 28,
    address: {
      street: "456 Oak St",
      city: "San Francisco",
      state: "CA",
      zip: "94102",
    },
    phone: "+1-555-5678",
    orders: [
      {
        orderId: 103,
        product: "Tablet",
        price: 500,
        date: "2024-03-05",
      },
      {
        orderId: 104,
        product: "Wireless Headphones",
        price: 150,
        date: "2024-03-20",
      },
    ],
  },
  {
    id: 3,
    name: "Alice Johnson",
    email: "alice.johnson@example.com",
    age: 35,
    address: {
      street: "789 Pine St",
      city: "Chicago",
      state: "IL",
      zip: "60601",
    },
    phone: "+1-555-9012",
    orders: [
      {
        orderId: 105,
        product: "Gaming Console",
        price: 400,
        date: "2024-04-10",
      },
      {
        orderId: 106,
        product: "4K TV",
        price: 900,
        date: "2024-05-01",
      },
    ],
  },
  {
    id: 4,
    name: "Michael Brown",
    email: "michael.brown@example.com",
    age: 40,
    address: {
      street: "135 Maple St",
      city: "Los Angeles",
      state: "CA",
      zip: "90001",
    },
    phone: "+1-555-3456",
    orders: [
      {
        orderId: 107,
        product: "Smartwatch",
        price: 250,
        date: "2024-06-12",
      },
      {
        orderId: 108,
        product: "Bluetooth Speaker",
        price: 100,
        date: "2024-07-18",
      },
    ],
  },
  {
    id: 5,
    name: "Emily White",
    email: "emily.white@example.com",
    age: 32,
    address: {
      street: "246 Birch St",
      city: "Houston",
      state: "TX",
      zip: "77002",
    },
    phone: "+1-555-7890",
    orders: [
      {
        orderId: 109,
        product: "Camera",
        price: 700,
        date: "2024-08-05",
      },
      {
        orderId: 110,
        product: "Tripod",
        price: 80,
        date: "2024-08-25",
      },
    ],
  },
  {
    id: 6,
    name: "David Green",
    email: "david.green@example.com",
    age: 27,
    address: {
      street: "789 Walnut St",
      city: "Seattle",
      state: "WA",
      zip: "98101",
    },
    phone: "+1-555-2345",
    orders: [
      {
        orderId: 111,
        product: "Desktop PC",
        price: 1500,
        date: "2024-09-10",
      },
      {
        orderId: 112,
        product: "Mechanical Keyboard",
        price: 120,
        date: "2024-09-30",
      },
    ],
  },
];

let dirName = "./dir1";
createDirecotry(dirName);
createFiles(dirName + "//file.json", JSON.stringify(data));
removeFile(dirName + "//file.json");
